config/routes.rb
Rails.application.routes.draw do
  resources :boxes do
    member do
      get "markdown"
    end
  end

  root "application#index"
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/application/index.html.haml
#app

:coffeescript
  $ ->
    new SApp.Routers.SAppRouter()
    Backbone.history.start()

app/views/boxes/_form.html.haml
= form_for @box do |f|
  - if @box.errors.any?
    #error_explanation
      %h2= "#{pluralize(@box.errors.count, "error")} prohibited this box from being saved:"
      %ul
        - @box.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/boxes/edit.html.haml
%h1 Editing box

= render 'form'

= link_to 'Show', @box
\|
= link_to 'Back', boxes_path

app/views/boxes/index.html.haml
#newBox
#boxes


%br

// = link_to 'New Box', new_box_path

:coffeescript
  $ ->
    boxes = new BBBox.Collections.BoxesCollection(#{@boxes.to_json.html_safe})
    boxes.each (box) ->
      view = new BBBox.Views.Boxes.BoxView({box : box})
      $("#boxes").append(view.render().el)
    newBox = new BBBox.Views.Boxes.NewView({boxes : boxes})
    $("#newBox").html(newBox.render().el)
    boxes.on "add", (box) ->
      view = new BBBox.Views.Boxes.BoxView({box : box})
      $("#boxes").append(view.render().el)

app/views/boxes/new.html.haml
%h1 New box

= render 'form'

= link_to 'Back', boxes_path

app/views/boxes/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @box.content

= link_to 'Edit', edit_box_path(@box)
\|
= link_to 'Back', boxes_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackboneBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>